{% set name = "napari-sdeconv" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sdeconv-{{ version }}.tar.gz
  sha256: 0aaccf46d88d1ebc264eabb4d935c5b9d14356f0c398d53bfa24c4c0e733cc33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.9
    - sdeconv >=0.1.0

test:
  imports:
    - napari_sdeconv
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sylvainprigent/napari-sdeconv
  summary: 2D and 3D image deconvolution
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
